#!/usr/bin/env python3
from __future__ import annotations

import os
import plistlib
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(os.environ.get("WHOS_AROUND_ME_ROOT", Path(__file__).resolve().parents[1])).resolve()
APP = ROOT / "apps" / "mobile"
ANDROID = APP / "android"
IOS = APP / "ios"

IDS = {
    "development": "com.dC0dez.Whosaroundme.dev",
    "test": "com.dC0dez.Whosaroundme.test",
    "staging": "com.dC0dez.Whosaroundme.staging",
    "production": "com.dC0dez.Whosaroundme",
}
DISPLAY = {
    "development": "Who's Around Me Dev",
    "test": "Who's Around Me Test",
    "staging": "Who's Around Me Staging",
    "production": "Who's Around Me",
}


def die(message: str) -> None:
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(2)


def patch_android() -> None:
    if not ANDROID.exists():
        die("Android project has not been generated by Flutter.")
    activities = list((ANDROID / "app" / "src" / "main" / "kotlin").rglob("MainActivity.kt"))
    if len(activities) != 1:
        die(f"Expected exactly one generated MainActivity.kt, found {len(activities)}")
    activity = activities[0]
    original = activity.read_text()
    match = re.search(r"^package\s+([\w.]+)\s*$", original, re.MULTILINE)
    if not match:
        die("Could not determine generated Android Kotlin package.")
    package_name = match.group(1)
    template = (ROOT / "native_overlays" / "android" / "MainActivity.kt.template").read_text()
    activity.write_text(template.replace("__ANDROID_PACKAGE__", package_name))

    manifest = ANDROID / "app" / "src" / "main" / "AndroidManifest.xml"
    text = manifest.read_text()
    for permission in (
        "android.permission.READ_CONTACTS",
        "android.permission.ACCESS_COARSE_LOCATION",
        "android.permission.ACCESS_FINE_LOCATION",
    ):
        if permission not in text:
            text = re.sub(
                r"(<manifest\b[^>]*>)",
                r'\1\n    <uses-permission android:name="' + permission + r'" />',
                text,
                count=1,
            )
    if "android.permission.ACCESS_BACKGROUND_LOCATION" in text:
        die("Generated Android manifest unexpectedly contains background location permission.")
    text = re.sub(r'android:label="[^"]*"', 'android:label="@string/app_name"', text, count=1)
    manifest.write_text(text)

    gradle_kts = ANDROID / "app" / "build.gradle.kts"
    if not gradle_kts.exists():
        die("Current Phase 6B overlay supports the Flutter Kotlin-DSL Android template only.")
    gradle = gradle_kts.read_text()
    marker = "// WHOS_AROUND_ME_ENV_FLAVORS"
    if marker not in gradle:
        flavor_block = f'''\n    {marker}\n    flavorDimensions += "environment"\n    productFlavors {{\n        create("development") {{\n            dimension = "environment"\n            applicationId = "{IDS['development']}"\n            resValue("string", "app_name", "{DISPLAY['development']}")\n        }}\n        create("qa") {{\n            dimension = "environment"\n            applicationId = "{IDS['test']}"\n            resValue("string", "app_name", "{DISPLAY['test']}")\n        }}\n        create("staging") {{\n            dimension = "environment"\n            applicationId = "{IDS['staging']}"\n            resValue("string", "app_name", "{DISPLAY['staging']}")\n        }}\n        create("production") {{\n            dimension = "environment"\n            applicationId = "{IDS['production']}"\n            resValue("string", "app_name", "{DISPLAY['production']}")\n        }}\n    }}\n'''
        if "    buildTypes {" in gradle:
            gradle = gradle.replace("    buildTypes {", flavor_block + "\n    buildTypes {", 1)
        else:
            die("Could not locate Android buildTypes block for flavor insertion.")
    dependency = 'implementation("com.google.android.gms:play-services-location:21.4.0")'
    if dependency not in gradle:
        if re.search(r"(?m)^dependencies\s*\{", gradle):
            gradle = re.sub(r"(?m)^dependencies\s*\{", "dependencies {\n    " + dependency, gradle, count=1)
        else:
            gradle += "\n\ndependencies {\n    " + dependency + "\n}\n"
    gradle_kts.write_text(gradle)


def patch_ios() -> None:
    if not IOS.exists():
        die("iOS project has not been generated by Flutter.")
    app_delegate = IOS / "Runner" / "AppDelegate.swift"
    if not app_delegate.exists():
        die("Generated iOS AppDelegate.swift not found.")
    shutil.copyfile(ROOT / "native_overlays" / "ios" / "AppDelegate.swift", app_delegate)

    info_plist = IOS / "Runner" / "Info.plist"
    with info_plist.open("rb") as handle:
        plist = plistlib.load(handle)
    plist["NSContactsUsageDescription"] = (
        "Who's Around Me uses contacts you allow so you can see and manage nearby people you already know."
    )
    plist["NSLocationWhenInUseUsageDescription"] = (
        "Who's Around Me uses your location while you use the app to calculate distances privately on this device."
    )
    plist.pop("NSLocationAlwaysAndWhenInUseUsageDescription", None)
    plist.pop("NSLocationAlwaysUsageDescription", None)
    background_modes = plist.get("UIBackgroundModes")
    if isinstance(background_modes, list) and "location" in background_modes:
        background_modes = [item for item in background_modes if item != "location"]
        if background_modes:
            plist["UIBackgroundModes"] = background_modes
        else:
            plist.pop("UIBackgroundModes", None)
    plist["CFBundleDisplayName"] = "Who's Around Me"
    with info_plist.open("wb") as handle:
        plistlib.dump(plist, handle, sort_keys=False)

    pbxproj = IOS / "Runner.xcodeproj" / "project.pbxproj"
    if pbxproj.exists():
        text = pbxproj.read_text()
        text = re.sub(
            r"PRODUCT_BUNDLE_IDENTIFIER\s*=\s*[^;]+;",
            f"PRODUCT_BUNDLE_IDENTIFIER = {IDS['production']};",
            text,
        )
        pbxproj.write_text(text)

    config_dir = IOS / "Flutter"
    config_dir.mkdir(parents=True, exist_ok=True)
    (config_dir / "WhosAroundMeEnvironmentIds.xcconfig").write_text(
        "// Reference values. Xcode flavor schemes must map their build configurations on macOS.\n"
        f"WHOSAROUNDME_BUNDLE_ID_DEVELOPMENT={IDS['development']}\n"
        f"WHOSAROUNDME_BUNDLE_ID_TEST={IDS['test']}\n"
        f"WHOSAROUNDME_BUNDLE_ID_STAGING={IDS['staging']}\n"
        f"WHOSAROUNDME_BUNDLE_ID_PRODUCTION={IDS['production']}\n"
    )


def main() -> None:
    patch_android()
    patch_ios()
    print("Applied Who's Around Me Phase 6B Android/iOS native overlays.")
    print("Android: four product flavors configured; foreground contacts/location bridge installed.")
    print("iOS: production bundle identifier + foreground bridge installed; multi-scheme flavor mapping remains a macOS/Xcode gate.")


if __name__ == "__main__":
    main()
